# This file was generated by GoReleaser. DO NOT EDIT.
class Mailchain < Formula
  desc "Secure, email-like messaging for blockchain addresses and accounts"
  homepage "https://mailchain.xyz"
  version "0.0.50"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/mailchain/mailchain/releases/download/v0.0.50/mailchain-0.0.50-macOS-64bit.tar.gz"
    sha256 "c8a295e0655b069d314268d2dc80a802941e87343f5c817e9a9680f374161d49"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/mailchain/mailchain/releases/download/v0.0.50/mailchain-0.0.50-Linux-64bit.tar.gz"
      sha256 "73eda3f76eaa4f2d6682c65824203d1867961d91d1067a11f20e36605288692a"
    end
  end

  def install
    bin.install "mailchain"
  end

  test do
    system "#{bin}/mailchain -v"
  end
end
