# This file was generated by GoReleaser. DO NOT EDIT.
class Mailchain < Formula
  desc "Secure, email-like messaging for blockchain addresses and accounts"
  homepage "https://mailchain.xyz"
  version "0.0.74"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/mailchain/mailchain/releases/download/v0.0.74/mailchain-v0.0.74-macOS-64bit.tar.gz"
    sha256 "472404864212b4d4521418c51aaa93df9ab93ee3ca22288c8af53b39704dd02c"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/mailchain/mailchain/releases/download/v0.0.74/mailchain-v0.0.74-Linux-64bit.tar.gz"
    sha256 "51149f1b24061c5f2da69d89c34bdfa09ada457d62282e74065eb4be38857da6"
  end

  def install
    bin.install "mailchain"
  end

  test do
    system "#{bin}/mailchain -v"
  end
end
