# This file was generated by GoReleaser. DO NOT EDIT.
class Mailchain < Formula
  desc "Secure, email-like messaging for blockchain addresses and accounts"
  homepage "https://mailchain.xyz"
  version "0.0.68"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/mailchain/mailchain/releases/download/v0.0.68/mailchain-v0.0.68-macOS-64bit.tar.gz"
    sha256 "588cc2b4e17258ee704545a080c821d7087cee79cce1c832247b384e4df7b338"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/mailchain/mailchain/releases/download/v0.0.68/mailchain-v0.0.68-Linux-64bit.tar.gz"
      sha256 "2d0428bcf3e1b64aa85c393a835117677fd05cedcaff993a0c1840397c48e80c"
    end
  end

  def install
    bin.install "mailchain"
  end

  test do
    system "#{bin}/mailchain -v"
  end
end
